version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      db_net:
        ipv4_address: 172.18.1.31

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    networks:
      db_net:
        ipv4_address: 172.18.1.32

networks:
  db_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
